services:
  backend:
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY_BACKEND}:$IMAGE_TAG
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_REGION}
    ports: 
     - '8000:8000'

  frontend:
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY_FRONTEND}:$IMAGE_TAG
    ports: 
     - '8501:8501'